### ISSUE TITLE
better explanation of components

### ISSUE THREAD

**Issue by wchristian** [Crendgrim/HaloHUD#10]
i installed it to use with hypixel's skyblock and due to various changes they do (no durability, no food) it wasn't entirely clear to me which parts of the ui i can disable without information loss

**Comment by Crendgrim** [comment]
Durability is "Tool", I concede that that is not the best name. Food should just be "Food".

**Comment by wchristian** [comment]
sorry, i wrote this when i was way too tired yesterday. here's a bit more detail on what i mean. to be clear: i'm only talking about the context of hypixel's skyblock. i am not *that* familiar with the vanilla mc mechanics.

this should maybe explain what all the 5 components are for, on the right side

![image](https://github.com/Crendgrim/HaloHUD/assets/175467/76476da9-cc58-46c7-a7d3-cb3e76c9bfa9)

should indicate whether this only means the armor bar only shows elytra durability and nothing else

![image](https://github.com/Crendgrim/HaloHUD/assets/175467/df717a5e-b8b2-427e-aaa0-bcda2832308b)

should indicate what the 4 secondary options for each of these are, i.e. extra parts of the bar, or colors to change the whole bar to. same for the health page

![image](https://github.com/Crendgrim/HaloHUD/assets/175467/029e7966-679b-4f1b-90b7-82bd4a95fa22)
![image](https://github.com/Crendgrim/HaloHUD/assets/175467/36824ce4-536c-4dcb-8b1b-3cd07c47d11a)

should indicate whether air is the only bar that is rendered by this

![image](https://github.com/Crendgrim/HaloHUD/assets/175467/d8f5667d-d11a-4a8c-85c9-f828dd117629)

**Comment by wchristian** [comment]
i'm also still trying to figure out whether the tool and attack bars do anything useful on skyblock

attack bar seems to indicate progress properly on the private island, it does not when mining things on public islands. pointing at an entity like minions on the private island also makes the attack bar pop up for no reason i can tell

tool bar i guess does nothing

**Comment by Crendgrim** [comment]
Ah, I see. I can add more context sensitive information there for sure!

Weird that the attack bar behaves differently on private vs. public islands. It has two functions. The first is the block break progress as you have figured out. The second is the "attack indicator". In vanilla, there is a cooldown between attacks, during which hitting an entity again inflicts massively reduced damage. There's also a vanilla attack indicator that this replaces. I can look to make it configurable that this bar only performs one of the two functions. I thought I already did that..

The tool bar is a durability bar for the tool you're currently holding (+ the one in your offhand, if any). Not sure if Skyblock has tool durability, I've never played on Hypixel.

**Comment by wchristian** [comment]
Turns out i was wrong. It's not about private vs public, but about block types. Skyblock has custom block breaking mechanics for **some** types of blocks, so they can provide resources, but not actually break, and even provide multiple resources and morph into other blocks.

The cooldown of attacks also happens on skyblock, but it might be handled server-side. Even with a slow axe i have not seen any useful visual indicator of when i am on cooldown, because the little sword icon disappears immediately, and appears everytime i attack even if i switch my mouse to turbo mode.

Also from what i can tell there is no durability for anything handheld either. :)
