### ISSUE TITLE
pointless ability to configure more than 5 segments

### ISSUE THREAD

**Issue by wchristian** [Crendgrim/HaloHUD#13]
the config allows adding more than 5 segments, even if they never get rendered

![2023-10-29_01 26 29](https://github.com/Crendgrim/HaloHUD/assets/175467/961d306e-3798-42b4-8151-eb63b84c6c33)

**Comment by Crendgrim** [comment]
Oh duh. This was a problem with the config library I'm using not allowing to set a size limit on lists. So I made a pull request to make that possible, and then completely forgot to update HaloHUD to make use of that..

**Comment by wchristian** [comment]
that's a familiar feeling :D
