### ISSUE TITLE
`halohud-4.3+1.21-neoforge` two problems

### ISSUE THREAD

**Issue by 3gf8jv4dv** [Crendgrim/HaloHUD#14]
_The Fabric version of the Halo HUD and other dependencies look to be working fine._

## Dependencies installed, but still says not installed

In a 1.21 NeoForge instance, when launching the game after installing Halo HUD and YACL, the game displays an error. :(

```
halohud-4.3+1.21-neoforge.jar
YetAnotherConfigLib-3.5.0+1.21-neoforge.jar
```

<details>
<summary>Preview</summary>

![](https://github.com/Crendgrim/HaloHUD/assets/158490944/7cf6f377-98a3-4f39-ab65-8be7baf001b5)

</details>

I noticed that the missing dependencies for the game prompts were different than for YACL itself.

The current `modId` used by the new YACL is `yet_another_config_lib_v3` instead of `yet_another_config_lib`.

## The game crashes

I tried manually modifying the `neoforge.mods.toml` file inside the Halo HUD jar file.

```diff
- modId = "yet_another_config_lib"
+ modId = "yet_another_config_lib_v3"
```
I thought I could enter the game without any problems, but it still does not work. It seems there is another problem.

_Crash log (Deleted)_

**Comment by Crendgrim** [comment]
Thank you for the detailed report! Good catch on the YACL id.

I have pushed a new version that should work properly!
