### ISSUE TITLE
Off-center (or not aligned to crosshair?)

### ISSUE THREAD

**Issue by april83c** [Crendgrim/HaloHUD#7]
When I use any GUI scale lower than 6 or Auto (on a 1440p display), the Halo HUD isn't aligned with the crosshair:

![image](https://user-images.githubusercontent.com/124521665/236647492-54acc87c-bf0e-461a-9879-5ea3927de482.png)

(and with GUI scale 6/Auto:)

![image](https://user-images.githubusercontent.com/124521665/236647536-c854bfd7-5a22-4c2b-b5e6-088b053dfa36.png)

To confirm it's not any of my mods, I made a new installation with just these mods, and it's still off-center:

![image](https://user-images.githubusercontent.com/124521665/236647573-d0898134-362e-44d2-bada-71138f4d1693.png)

My settings:

![image](https://user-images.githubusercontent.com/124521665/236647596-31ecf23f-345d-4e5e-bcff-f6285964922f.png)

**Comment by Crendgrim** [comment]
Ah heck, centering things is always a mess. I must have broken it while changing the way I draw the halos... thank you for the detailed report.

The underlying problem is that *the crosshair* is not centered either, see https://bugs.mojang.com/browse/MC-157252

**Comment by april83c** [comment]
Workaround: [this mod](https://modrinth.com/mod/custom-crosshair-mod) seems to make the crosshair properly centered(?)

**Comment by Crendgrim** [comment]
Alternatively, DynamicCrosshair can also center the crosshair now.
